### ISSUE TITLE
namespace error

### ISSUE THREAD

**Issue by twilly86** [deyunote/EntityFramework.Include#2]
I am getting the following error on build.  Intellisense works fine for me but when building the namespace can't be found.

error CS0234: The type or namespace name 'Include' does not exist in the namespace 'EntityFramework' (are you missing an assembly reference?)

**Comment by twilly86** [comment]
need to support 4.6.1

**Comment by deyunote** [comment]
Thx for your comment.
Maybe, I have to create version-specific .csproj :eyes:
